name: Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: MyAPI_RohanCodeHub-main
        run: dotnet restore

      - name: Build Backend
        working-directory: MyAPI_RohanCodeHub-main
        run: dotnet build --configuration Release --no-restore